"""
Approval Workflow Engine - User Approval System for MCP Suggestions

Manages the complete lifecycle of MCP suggestions from generation to execution.
All executions require explicit user approval.
"""
from typing import Dict, Any, List, Optional
from datetime import datetime
from enum import Enum
import uuid
import logging
from collections import defaultdict

logger = logging.getLogger(__name__)


class ApprovalStatus(Enum):
    """Approval workflow states"""
    PENDING = "pending"            # Waiting for user review
    APPROVED = "approved"          # User approved, ready for execution
    REJECTED = "rejected"          # User rejected
    EXECUTING = "executing"        # Currently being executed
    EXECUTED = "executed"          # Successfully executed
    FAILED = "failed"              # Execution failed
    ROLLED_BACK = "rolled_back"    # Changes were reverted
    EXPIRED = "expired"            # Approval request expired


class ApprovalWorkflow:
    """
    Manages user approval workflow for MCP suggestions.

    Flow:
    1. Suggestion generated by MCP → submit_for_approval()
    2. User reviews → approve() or reject()
    3. If approved → execute_approved()
    4. Track execution → mark_executed() or mark_failed()
    """

    def __init__(self, ds_id: str):
        """
        Initialize approval workflow for a datasource.

        Args:
            ds_id: Datasource identifier
        """
        self.ds_id = ds_id

        # In-memory storage (would use database in production)
        self.pending_suggestions: Dict[str, Dict[str, Any]] = {}

        # Execution history for audit
        self.execution_history: List[Dict[str, Any]] = []

        # Statistics
        self.stats = defaultdict(int)

        logger.info(f"Approval workflow initialized for datasource: {ds_id}")

    def submit_for_approval(
        self,
        suggestion: Dict[str, Any]
    ) -> str:
        """
        Submit MCP suggestion for user approval.

        Args:
            suggestion: Validated MCP suggestion with safety metadata

        Returns:
            approval_id: Unique identifier for tracking approval

        Example:
            approval_id = workflow.submit_for_approval(validated_suggestion)
        """
        # Generate unique approval ID
        approval_id = f"approval-{uuid.uuid4()}"

        # Create approval record
        approval_record = {
            "approval_id": approval_id,
            "ds_id": self.ds_id,
            "suggestion": suggestion,
            "status": ApprovalStatus.PENDING.value,

            # Timestamps
            "submitted_at": datetime.utcnow().isoformat(),
            "approved_at": None,
            "rejected_at": None,
            "executed_at": None,
            "expires_at": None,  # Optional: auto-expire after N hours

            # User tracking
            "approved_by": None,
            "rejected_by": None,

            # Execution tracking
            "execution_result": None,
            "execution_error": None,
            "rollback_available": False,

            # Metadata
            "rejection_reason": None,
            "notes": []
        }

        self.pending_suggestions[approval_id] = approval_record
        self.stats["submitted"] += 1

        logger.info(
            f"Suggestion submitted for approval: {approval_id} "
            f"(risk={suggestion.get('risk_level')})"
        )

        return approval_id

    def approve(
        self,
        approval_id: str,
        user_id: str,
        notes: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        User approves a suggestion.

        Args:
            approval_id: Approval identifier
            user_id: User who approved
            notes: Optional approval notes

        Returns:
            Updated approval record

        Raises:
            ValueError: If approval_id not found or invalid status
        """
        if approval_id not in self.pending_suggestions:
            raise ValueError(f"Approval ID not found: {approval_id}")

        record = self.pending_suggestions[approval_id]

        # Validate current status
        if record["status"] != ApprovalStatus.PENDING.value:
            raise ValueError(
                f"Cannot approve: current status is {record['status']}"
            )

        # Update record
        record["status"] = ApprovalStatus.APPROVED.value
        record["approved_at"] = datetime.utcnow().isoformat()
        record["approved_by"] = user_id

        if notes:
            record["notes"].append({
                "timestamp": datetime.utcnow().isoformat(),
                "user": user_id,
                "type": "approval",
                "content": notes
            })

        self.stats["approved"] += 1

        logger.info(f"Suggestion approved: {approval_id} by {user_id}")

        return record

    def reject(
        self,
        approval_id: str,
        user_id: str,
        reason: str
    ) -> Dict[str, Any]:
        """
        User rejects a suggestion.

        Args:
            approval_id: Approval identifier
            user_id: User who rejected
            reason: Reason for rejection

        Returns:
            Updated approval record
        """
        if approval_id not in self.pending_suggestions:
            raise ValueError(f"Approval ID not found: {approval_id}")

        record = self.pending_suggestions[approval_id]

        # Validate current status
        if record["status"] not in [ApprovalStatus.PENDING.value, ApprovalStatus.APPROVED.value]:
            raise ValueError(
                f"Cannot reject: current status is {record['status']}"
            )

        # Update record
        record["status"] = ApprovalStatus.REJECTED.value
        record["rejected_at"] = datetime.utcnow().isoformat()
        record["rejected_by"] = user_id
        record["rejection_reason"] = reason

        record["notes"].append({
            "timestamp": datetime.utcnow().isoformat(),
            "user": user_id,
            "type": "rejection",
            "content": reason
        })

        self.stats["rejected"] += 1

        logger.info(f"Suggestion rejected: {approval_id} by {user_id} - {reason}")

        return record

    def mark_executing(self, approval_id: str) -> Dict[str, Any]:
        """
        Mark suggestion as currently executing.

        Args:
            approval_id: Approval identifier

        Returns:
            Updated approval record
        """
        if approval_id not in self.pending_suggestions:
            raise ValueError(f"Approval ID not found: {approval_id}")

        record = self.pending_suggestions[approval_id]

        # Validate must be approved
        if record["status"] != ApprovalStatus.APPROVED.value:
            raise ValueError(
                f"Cannot execute: must be approved first (current: {record['status']})"
            )

        record["status"] = ApprovalStatus.EXECUTING.value

        logger.info(f"Execution started: {approval_id}")

        return record

    def mark_executed(
        self,
        approval_id: str,
        execution_result: Dict[str, Any],
        rollback_available: bool = False
    ) -> Dict[str, Any]:
        """
        Mark suggestion as successfully executed.

        Args:
            approval_id: Approval identifier
            execution_result: Results from execution
            rollback_available: Whether rollback is possible

        Returns:
            Updated approval record
        """
        if approval_id not in self.pending_suggestions:
            raise ValueError(f"Approval ID not found: {approval_id}")

        record = self.pending_suggestions[approval_id]

        # Update record
        record["status"] = ApprovalStatus.EXECUTED.value
        record["executed_at"] = datetime.utcnow().isoformat()
        record["execution_result"] = execution_result
        record["rollback_available"] = rollback_available

        # Move to execution history
        self.execution_history.append(record)

        self.stats["executed"] += 1

        logger.info(f"Execution completed: {approval_id}")

        return record

    def mark_failed(
        self,
        approval_id: str,
        error: str
    ) -> Dict[str, Any]:
        """
        Mark suggestion execution as failed.

        Args:
            approval_id: Approval identifier
            error: Error message

        Returns:
            Updated approval record
        """
        if approval_id not in self.pending_suggestions:
            raise ValueError(f"Approval ID not found: {approval_id}")

        record = self.pending_suggestions[approval_id]

        # Update record
        record["status"] = ApprovalStatus.FAILED.value
        record["execution_error"] = error
        record["executed_at"] = datetime.utcnow().isoformat()

        self.stats["failed"] += 1

        logger.error(f"Execution failed: {approval_id} - {error}")

        return record

    def get_pending_approvals(self) -> List[Dict[str, Any]]:
        """
        Get all pending approval requests.

        Returns:
            List of pending approval records
        """
        return [
            record for record in self.pending_suggestions.values()
            if record["status"] == ApprovalStatus.PENDING.value
        ]

    def get_approved_pending_execution(self) -> List[Dict[str, Any]]:
        """
        Get all approved suggestions waiting for execution.

        Returns:
            List of approved but not yet executed records
        """
        return [
            record for record in self.pending_suggestions.values()
            if record["status"] == ApprovalStatus.APPROVED.value
        ]

    def get_approval_by_id(self, approval_id: str) -> Optional[Dict[str, Any]]:
        """
        Get approval record by ID.

        Args:
            approval_id: Approval identifier

        Returns:
            Approval record or None if not found
        """
        return self.pending_suggestions.get(approval_id)

    def get_execution_history(
        self,
        limit: int = 50,
        status_filter: Optional[str] = None
    ) -> List[Dict[str, Any]]:
        """
        Get execution history.

        Args:
            limit: Maximum number of records
            status_filter: Filter by status (executed, failed, etc.)

        Returns:
            List of historical records
        """
        history = self.execution_history

        if status_filter:
            history = [h for h in history if h["status"] == status_filter]

        # Sort by execution time (newest first)
        history = sorted(
            history,
            key=lambda x: x.get("executed_at", ""),
            reverse=True
        )

        return history[:limit]

    def get_statistics(self) -> Dict[str, int]:
        """
        Get workflow statistics.

        Returns:
            Statistics dictionary
        """
        return {
            "total_submitted": self.stats["submitted"],
            "total_approved": self.stats["approved"],
            "total_rejected": self.stats["rejected"],
            "total_executed": self.stats["executed"],
            "total_failed": self.stats["failed"],
            "currently_pending": len(self.get_pending_approvals()),
            "awaiting_execution": len(self.get_approved_pending_execution())
        }

    def cleanup_old_records(self, days: int = 30):
        """
        Clean up old approval records (executed/rejected/failed).

        Args:
            days: Keep records newer than this many days
        """
        # This would implement cleanup logic for old records
        # For now, just log
        logger.info(f"Cleanup requested: removing records older than {days} days")

        # Implementation would filter by timestamp and remove old records
        pass


# Global workflow instances (keyed by ds_id)
_workflows: Dict[str, ApprovalWorkflow] = {}


def get_workflow(ds_id: str) -> ApprovalWorkflow:
    """
    Get or create approval workflow for a datasource.

    Args:
        ds_id: Datasource identifier

    Returns:
        ApprovalWorkflow instance
    """
    if ds_id not in _workflows:
        _workflows[ds_id] = ApprovalWorkflow(ds_id)

    return _workflows[ds_id]
