"""
Approval Workflow Engine - User Approval System for MCP Suggestions

Manages the complete lifecycle of MCP suggestions from generation to execution.
All executions require explicit user approval.

Persistence: backed by approval_store (SQLite). PENDING/APPROVED/EXECUTED records
survive restarts, and every state transition writes an immutable audit_log row.
"""
from typing import Dict, Any, List, Optional
from datetime import datetime
from enum import Enum
import uuid
import logging

from . import approval_store

logger = logging.getLogger(__name__)


class ApprovalStatus(Enum):
    """Approval workflow states"""
    PENDING = "pending"            # Waiting for user review
    APPROVED = "approved"          # User approved, ready for execution
    REJECTED = "rejected"          # User rejected
    EXECUTING = "executing"        # Currently being executed
    EXECUTED = "executed"          # Successfully executed
    FAILED = "failed"              # Execution failed
    ROLLED_BACK = "rolled_back"    # Changes were reverted
    EXPIRED = "expired"            # Approval request expired


class ApprovalWorkflow:
    """
    Manages user approval workflow for MCP suggestions, backed by approval_store.

    Flow:
    1. Suggestion generated by MCP → submit_for_approval()
    2. User reviews → approve() or reject()
    3. If approved → mark_executing() → mark_executed() / mark_failed()
    Every transition is recorded in the append-only audit log.
    """

    def __init__(self, ds_id: str):
        self.ds_id = ds_id
        approval_store.init_db()
        logger.info(f"Approval workflow initialized for datasource: {ds_id}")

    # --- lifecycle -----------------------------------------------------------

    def submit_for_approval(
        self,
        suggestion: Dict[str, Any],
        submitted_by: Optional[str] = None,
    ) -> str:
        """Submit an (already guardrail-screened) suggestion for user approval."""
        approval_id = f"approval-{uuid.uuid4()}"
        approval_store.insert_approval(
            approval_id=approval_id,
            ds_id=self.ds_id,
            suggestion=suggestion,
            status=ApprovalStatus.PENDING.value,
            submitted_by=submitted_by,
        )
        approval_store.append_audit(
            "submit", ds_id=self.ds_id, approval_id=approval_id, actor=submitted_by,
            detail={"risk_level": suggestion.get("risk_level"), "sql": (suggestion.get("sql") or "")[:200]},
        )
        logger.info(f"Suggestion submitted for approval: {approval_id} (risk={suggestion.get('risk_level')})")
        return approval_id

    def approve(self, approval_id: str, user_id: str, notes: Optional[str] = None) -> Dict[str, Any]:
        record = self._require(approval_id)
        if record["status"] != ApprovalStatus.PENDING.value:
            raise ValueError(f"Cannot approve: current status is {record['status']}")

        note_list = record["notes"]
        if notes:
            note_list.append({
                "timestamp": datetime.utcnow().isoformat(),
                "user": user_id, "type": "approval", "content": notes,
            })
        approval_store.update_approval(
            approval_id,
            status=ApprovalStatus.APPROVED.value,
            approved_at=datetime.utcnow().isoformat(),
            approved_by=user_id,
            notes=note_list,
        )
        approval_store.append_audit("approve", ds_id=self.ds_id, approval_id=approval_id,
                                    actor=user_id, detail={"notes": notes})
        logger.info(f"Suggestion approved: {approval_id} by {user_id}")
        return approval_store.get_approval(approval_id)

    def reject(self, approval_id: str, user_id: str, reason: str) -> Dict[str, Any]:
        record = self._require(approval_id)
        if record["status"] not in (ApprovalStatus.PENDING.value, ApprovalStatus.APPROVED.value):
            raise ValueError(f"Cannot reject: current status is {record['status']}")

        note_list = record["notes"]
        note_list.append({
            "timestamp": datetime.utcnow().isoformat(),
            "user": user_id, "type": "rejection", "content": reason,
        })
        approval_store.update_approval(
            approval_id,
            status=ApprovalStatus.REJECTED.value,
            rejected_at=datetime.utcnow().isoformat(),
            rejected_by=user_id,
            rejection_reason=reason,
            notes=note_list,
        )
        approval_store.append_audit("reject", ds_id=self.ds_id, approval_id=approval_id,
                                    actor=user_id, detail={"reason": reason})
        logger.info(f"Suggestion rejected: {approval_id} by {user_id} - {reason}")
        return approval_store.get_approval(approval_id)

    def mark_executing(self, approval_id: str) -> Dict[str, Any]:
        record = self._require(approval_id)
        if record["status"] != ApprovalStatus.APPROVED.value:
            raise ValueError(f"Cannot execute: must be approved first (current: {record['status']})")
        approval_store.update_approval(approval_id, status=ApprovalStatus.EXECUTING.value)
        approval_store.append_audit("execute", ds_id=self.ds_id, approval_id=approval_id)
        logger.info(f"Execution started: {approval_id}")
        return approval_store.get_approval(approval_id)

    def mark_executed(
        self,
        approval_id: str,
        execution_result: Dict[str, Any],
        rollback_available: bool = False,
        rollback_sql: Optional[str] = None,
    ) -> Dict[str, Any]:
        self._require(approval_id)
        approval_store.update_approval(
            approval_id,
            status=ApprovalStatus.EXECUTED.value,
            executed_at=datetime.utcnow().isoformat(),
            execution_result=execution_result,
            rollback_available=rollback_available,
            rollback_sql=rollback_sql,
        )
        approval_store.append_audit("executed", ds_id=self.ds_id, approval_id=approval_id,
                                    detail={"rollback_available": rollback_available})
        logger.info(f"Execution completed: {approval_id}")
        return approval_store.get_approval(approval_id)

    def mark_failed(self, approval_id: str, error: str) -> Dict[str, Any]:
        self._require(approval_id)
        approval_store.update_approval(
            approval_id,
            status=ApprovalStatus.FAILED.value,
            executed_at=datetime.utcnow().isoformat(),
            error=error,
        )
        approval_store.append_audit("fail", ds_id=self.ds_id, approval_id=approval_id,
                                    detail={"error": error[:500]})
        logger.error(f"Execution failed: {approval_id} - {error}")
        return approval_store.get_approval(approval_id)

    def mark_rolled_back(self, approval_id: str, detail: Optional[str] = None) -> Dict[str, Any]:
        self._require(approval_id)
        approval_store.update_approval(approval_id, status=ApprovalStatus.ROLLED_BACK.value)
        approval_store.append_audit("rollback", ds_id=self.ds_id, approval_id=approval_id,
                                    detail={"detail": detail})
        logger.info(f"Execution rolled back: {approval_id}")
        return approval_store.get_approval(approval_id)

    # --- queries -------------------------------------------------------------

    def get_pending_approvals(self) -> List[Dict[str, Any]]:
        return approval_store.list_by_status(self.ds_id, ApprovalStatus.PENDING.value)

    def get_approved_pending_execution(self) -> List[Dict[str, Any]]:
        return approval_store.list_by_status(self.ds_id, ApprovalStatus.APPROVED.value)

    def get_approval_by_id(self, approval_id: str) -> Optional[Dict[str, Any]]:
        record = approval_store.get_approval(approval_id)
        # Isolate per-datasource lookups, matching the previous in-memory behavior.
        if record and record.get("ds_id") != self.ds_id:
            return None
        return record

    def get_execution_history(self, limit: int = 50, status_filter: Optional[str] = None) -> List[Dict[str, Any]]:
        return approval_store.list_history(self.ds_id, limit=limit, status_filter=status_filter)

    def get_statistics(self) -> Dict[str, int]:
        counts = approval_store.counts_by_status(self.ds_id)
        return {
            "total_submitted": sum(counts.values()),
            "total_approved": counts.get(ApprovalStatus.APPROVED.value, 0),
            "total_rejected": counts.get(ApprovalStatus.REJECTED.value, 0),
            "total_executed": counts.get(ApprovalStatus.EXECUTED.value, 0),
            "total_failed": counts.get(ApprovalStatus.FAILED.value, 0),
            "currently_pending": counts.get(ApprovalStatus.PENDING.value, 0),
            "awaiting_execution": counts.get(ApprovalStatus.APPROVED.value, 0),
        }

    def cleanup_old_records(self, days: int = 30) -> int:
        """Remove old terminal approval rows. Audit rows are never deleted."""
        removed = approval_store.cleanup_old_records(days=days)
        approval_store.append_audit("cleanup", ds_id=self.ds_id, detail={"days": days, "removed": removed})
        return removed

    # --- helpers -------------------------------------------------------------

    def _require(self, approval_id: str) -> Dict[str, Any]:
        record = self.get_approval_by_id(approval_id)
        if not record:
            raise ValueError(f"Approval ID not found: {approval_id}")
        return record


# Global workflow instances (keyed by ds_id). The durable state lives in
# approval_store; these are just thin per-datasource handles.
_workflows: Dict[str, ApprovalWorkflow] = {}


def get_workflow(ds_id: str) -> ApprovalWorkflow:
    """Get or create the approval workflow handle for a datasource."""
    if ds_id not in _workflows:
        _workflows[ds_id] = ApprovalWorkflow(ds_id)
    return _workflows[ds_id]
