"""
In-memory suggestion registry with TTL-based eviction.

Stores optimization suggestions generated by the /suggestions/analyze endpoint so
that clients can later reference them by ID when calling /suggestions/apply.
"""

from __future__ import annotations

from dataclasses import dataclass
from threading import RLock
from time import time
from typing import Dict, Iterable, List, Tuple

from ..schemas import Suggestion

DEFAULT_TTL_SECONDS = 60 * 60  # 1 hour
MAX_STORED_SUGGESTIONS = 5_000  # soft cap to avoid unbounded growth


@dataclass
class StoredSuggestion:
    suggestion: Suggestion
    datasource_id: str
    stored_at: float
    ttl_seconds: int

    def is_expired(self, now: float | None = None) -> bool:
        now = now or time()
        return now - self.stored_at > self.ttl_seconds


class SuggestionStore:
    """
    Thread-safe in-memory registry keyed by suggestion ID.

    This lightweight store keeps recent suggestions available for follow-up apply
    calls without introducing new durable storage requirements.
    """

    def __init__(self):
        self._lock = RLock()
        self._items: Dict[str, StoredSuggestion] = {}

    def add_all(
        self,
        datasource_id: str,
        suggestions: Iterable[Suggestion],
        ttl_seconds: int = DEFAULT_TTL_SECONDS,
    ) -> None:
        """Insert multiple suggestions for a datasource."""
        now = time()
        with self._lock:
            for suggestion in suggestions:
                self._items[suggestion.id] = StoredSuggestion(
                    suggestion=suggestion,
                    datasource_id=datasource_id,
                    stored_at=now,
                    ttl_seconds=ttl_seconds,
                )
            self._prune(max_size=MAX_STORED_SUGGESTIONS)

    def get_many(
        self, suggestion_ids: Iterable[str], datasource_id: str | None = None
    ) -> Tuple[List[Suggestion], List[str]]:
        """
        Retrieve suggestions by ID.

        Returns:
            (found, missing) where found is a list of Suggestion objects and missing
            contains IDs that were not present (expired or never seen).
        """
        now = time()
        found: List[Suggestion] = []
        missing: List[str] = []

        with self._lock:
            for suggestion_id in suggestion_ids:
                stored = self._items.get(suggestion_id)
                if not stored:
                    missing.append(suggestion_id)
                    continue

                if datasource_id and stored.datasource_id != datasource_id:
                    missing.append(suggestion_id)
                    continue
                if stored.is_expired(now):
                    # drop expired entry
                    del self._items[suggestion_id]
                    missing.append(suggestion_id)
                    continue

                found.append(stored.suggestion)

        return found, missing

    def _prune(self, max_size: int) -> None:
        """Remove expired entries and enforce soft size limit."""
        now = time()
        expired_keys = [
            suggestion_id
            for suggestion_id, stored in self._items.items()
            if stored.is_expired(now)
        ]
        for suggestion_id in expired_keys:
            del self._items[suggestion_id]

        if len(self._items) <= max_size:
            return

        # Remove the oldest entries until we meet the soft cap.
        sorted_items = sorted(
            self._items.items(), key=lambda item: item[1].stored_at
        )
        for suggestion_id, _ in sorted_items:
            if len(self._items) <= max_size:
                break
            del self._items[suggestion_id]

    def clear_for_datasource(self, datasource_id: str) -> None:
        with self._lock:
            keys = [
                suggestion_id
                for suggestion_id, stored in self._items.items()
                if stored.datasource_id == datasource_id
            ]
            for suggestion_id in keys:
                del self._items[suggestion_id]


# Singleton store used across the application
suggestion_store = SuggestionStore()
